### ISSUE TITLE
Archive not updated when adding new Page

### ISSUE THREAD

**Issue by johann-sonntagbauer** [Sommerregen/grav-plugin-archive-plus#12]
When I activate the plugin, the archive gets generated correctly.
Now after adding a new Page the archiv is not updated.

After deactivating and activating the plugin again, the archiv is now updated.

Side Note: I also have the Simple Search plugin activated. Here the new page gets indexed automatically.

archive_plus.yaml
```yaml
enabled: true
built_in_css: true
show:
  counter: true
  year: true
  month: true
  items: true
limit:
  year: 2
  month: 12
  items: 40
order:
  by: date
  dir: desc
filter_combinator: and
filters:
  category: blog
```
